"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestLiveRoboticsUI,
	#superclass : #PackageManifest,
	#category : #'LiveRobotics-UI'
}

{ #category : #'code-critics' }
ManifestLiveRoboticsUI class >> ruleRBCascadedNextPutAllsRuleV1FalsePositive [
	^ #(#(#(#RGClassDefinition #(#LRPErrorHandlerUI)) #'2016-05-27T11:57:05.689531-03:00') )
]
